language: node_js
sudo: false

# Installation
node_js: 5.0.0
cache:
  directories:
    - node_modules
    - public/bower_components

# Testing
script: npm test

# Analysis
env:
  CODECLIMATE_REPO_TOKEN: 1251f2891d75a12f4529fd596ba0f99aec3e7858cb3db486ecc3e2bc0721367c
after_script: npm run upload-coverage

# Deploying
deploy:
  provider: heroku
  api_key:
    secure: o9Vp4MYPOnWWRwfMM0GmJvHO90wnWlgC15anBPZVWTweVWqZoIxVlxae6KcuYNbSUeaFqoevlkLFYizNATIocB6sZuY11Lo86QVyEdnX+aU+pHtdbZzuoZQhJUZHgiclqcDZPGHAeML+9X7L9FQ7bIk7hoPRyWIA2x0PAoUv4Dk=
  app: rosesearch
  on:
    repo: nickmccurdy/rose
