language: node_js
sudo: false

# Installation
node_js: node
cache:
  directories:
    - node_modules

# Analysis
env:
  CODECLIMATE_REPO_TOKEN: 1251f2891d75a12f4529fd596ba0f99aec3e7858cb3db486ecc3e2bc0721367c
after_script: npm run upload-coverage

# Deploying
deploy:
  provider: heroku
  api_key:
    secure: GZ+jojxiLHXzAuWG+2o+dFV4YsPDNTq6IFCyKmVFTovhVbCJcmMgwrgJgbkq7lit0VFyKYN974xDnefZLJzlzil/bO45sugyEs6ORl1Qe5OwPzoZOdbAupUTGeI+7aT4RSr16pLRCbFnYnswSuesRsMvggM3BjBt+n73AAkijwU=
  app: rosesearch
  on:
    repo: nickmccurdy/rose
