language: node_js
sudo: false

# Installation
node_js: 5.0.0
services: mongodb
cache:
  directories:
    - node_modules
    - public/bower_components

# Testing
script: npm test

# Deploying
deploy:
  provider: heroku
  api_key:
    secure: o9Vp4MYPOnWWRwfMM0GmJvHO90wnWlgC15anBPZVWTweVWqZoIxVlxae6KcuYNbSUeaFqoevlkLFYizNATIocB6sZuY11Lo86QVyEdnX+aU+pHtdbZzuoZQhJUZHgiclqcDZPGHAeML+9X7L9FQ7bIk7hoPRyWIA2x0PAoUv4Dk=
  app: rosesearch
  on:
    repo: nickmccurdy/rose
