language: node_js
sudo: false
node_js:
  - 4
  - 0.12
  - "0.10"
services: mongodb
addons:
  code_climate:
    repo_token: 1251f2891d75a12f4529fd596ba0f99aec3e7858cb3db486ecc3e2bc0721367c
script:
- npm test --coverage
after_script:
- node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: heroku
  api_key:
    secure: xRofDBoZpKyQbBfhhLWBWTWT9ocY4cFMnHmWDyDnnJtFfO6cplD8iIsK/wzfb4K/qvZcm7Ethf19J2t8kvOWzIcLQAPrViQBFpatC2xfv4wjA+ic8YIAzihakNRsMokbXhFnbbiwMwjG9SpTJKLuYpN/yoSp+3qAU5QAvpXlU9Q=
  app: rosesearch
  on:
    repo: nicolasmccurdy/rose
