language: node_js
sudo: false

# Installation
node_js: 5.0.0
services: mongodb
cache:
  directories:
    - node_modules
    - public/bower_components

# Testing
script: npm test

# Deploying
deploy:
  provider: heroku
  api_key:
    secure: xRofDBoZpKyQbBfhhLWBWTWT9ocY4cFMnHmWDyDnnJtFfO6cplD8iIsK/wzfb4K/qvZcm7Ethf19J2t8kvOWzIcLQAPrViQBFpatC2xfv4wjA+ic8YIAzihakNRsMokbXhFnbbiwMwjG9SpTJKLuYpN/yoSp+3qAU5QAvpXlU9Q=
  app: rosesearch
  on:
    repo: nickmccurdy/rose
